#!/bin/sh

set -e

case "$1" in
  configure)
      if [ -e /usr/bin/chromium-browser ] ; then
	    update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/chromium-browser 90
      fi

      if [ -e /usr/bin/chromium ] ; then
	    update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/chromium 60
      fi

      if [ -e /home/pi/.config/chromium/Default/Preferences ] ; then
        sed /home/pi/.config/chromium/Default/Preferences -i -e 's/"default_content_setting_values":{"plugins":2}/"default_content_setting_values":{"plugins":0}/'
      fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
      echo "postinst called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac



exit 0
