#!/bin/sh

ARCH=$(dpkg --print-architecture)

if [ "$ARCH" !=  "armhf" ] ; then
	if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" ]; then
		dpkg-divert --package rpi-chromium-mods --rename --remove /usr/share/chromium/master_preferences
	fi
	dpkg-maintscript-helper rm_conffile /etc/chromium/master_preferences 20170809 -- "$@"
fi

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

